apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Homepage
  allowedHosts: |
    - homepage.home.coryair.com
  services.yaml: |
    - Apps:
        - My First Service:
            href: http://localhost/
            description: Homepage is awesome

    - Infra:
        - OPNSense:
            href: https://router.home.coryair.com
            description: OPNSense Router

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is ðŸ˜Ž
  widgets.yaml: |
    []
